<?php

namespace Database\Seeders;

use App\Models\Image;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        DB::table('images')->delete();

        $images = array(
            ["name"=>"ad.svg","country"=>"Andorra"],
            ["name"=>"ae.svg","country"=>"United Arab Emirates"],
            ["name"=>"af.svg","country"=>"Afghanistan"],
            ["name"=>"ag.svg","country"=>"Antigua And Barbuda"],
            ["name"=>"ai.svg","country"=>"Anguilla"],
            ["name"=>"al.svg","country"=>"Albania"],
            ["name"=>"am.svg","country"=>"Armenia"],
            ["name"=>"ao.svg","country"=>"Angola"],
            ["name"=>"aq.svg","country"=>"Antarctica"],
            ["name"=>"ar.svg","country"=>"Argentina"],
            ["name"=>"as.svg","country"=>"American Samoa"],
            ["name"=>"at.svg","country"=>"Austria"],
            ["name"=>"au.svg","country"=>"Australia"],
            ["name"=>"aw.svg","country"=>"Aruba"],
            ["name"=>"ax.svg","country"=>"Åland Islands"],
            ["name"=>"az.svg","country"=>"Azerbaijan"],
            ["name"=>"ba.svg","country"=>"Bosnia And Herzegovina"],
            ["name"=>"bb.svg","country"=>"Barbados"],
            ["name"=>"bd.svg","country"=>"Bangladesh"],
            ["name"=>"be.svg","country"=>"Belgium"],
            ["name"=>"bf.svg","country"=>"Burkina Faso"],
            ["name"=>"bg.svg","country"=>"Bulgaria"],
            ["name"=>"bh.svg","country"=>"Bahrain"],
            ["name"=>"bi.svg","country"=>"Burundi"],
            ["name"=>"bj.svg","country"=>"Benin"],
            ["name"=>"bl.svg","country"=>"Saint Barthélemy"],
            ["name"=>"bm.svg","country"=>"Bermuda"],
            ["name"=>"bn.svg","country"=>"Brunei Darussalam"],
            ["name"=>"bo.svg","country"=>"Bolivia, Plurinational State Of"],
            ["name"=>"bq.svg","country"=>"Caribbean Netherlands"],
            ["name"=>"br.svg","country"=>"Brazil"],
            ["name"=>"bs.svg","country"=>"Bahamas"],
            ["name"=>"bt.svg","country"=>"Bhutan"],
            ["name"=>"bv.svg","country"=>"Bouvet Island"],
            ["name"=>"bw.svg","country"=>"Botswana"],
            ["name"=>"by.svg","country"=>"Belarus"],
            ["name"=>"bz.svg","country"=>"Belize"],
            ["name"=>"ca.svg","country"=>"Canada"],
            ["name"=>"cc.svg","country"=>"Cocos (Keeling) Islands"],
            ["name"=>"cd.svg","country"=>"Congo, The Democratic Republic Of The"],
            ["name"=>"cf.svg","country"=>"Central African Republic"],
            ["name"=>"cg.svg","country"=>"Republic Of The Congo"],
            ["name"=>"ch.svg","country"=>"Switzerland"],
            ["name"=>"ci.svg","country"=>"Côte D'Ivoire"],
            ["name"=>"ck.svg","country"=>"Cook Islands"],
            ["name"=>"cl.svg","country"=>"Chile"],
            ["name"=>"cm.svg","country"=>"Cameroon"],
            ["name"=>"cn.svg","country"=>"China (People's Republic Of China)"],
            ["name"=>"co.svg","country"=>"Colombia"],
            ["name"=>"cr.svg","country"=>"Costa Rica"],
            ["name"=>"cu.svg","country"=>"Cuba"],
            ["name"=>"cv.svg","country"=>"Cape Verde"],
            ["name"=>"cw.svg","country"=>"Curaçao"],
            ["name"=>"cx.svg","country"=>"Christmas Island"],
            ["name"=>"cy.svg","country"=>"Cyprus"],
            ["name"=>"cz.svg","country"=>"Czech Republic"],
            ["name"=>"de.svg","country"=>"Germany"],
            ["name"=>"dj.svg","country"=>"Djibouti"],
            ["name"=>"dk.svg","country"=>"Denmark"],
            ["name"=>"dm.svg","country"=>"Dominica"],
            ["name"=>"do.svg","country"=>"Dominican Republic"],
            ["name"=>"dz.svg","country"=>"Algeria"],
            ["name"=>"ec.svg","country"=>"Ecuador"],
            ["name"=>"ee.svg","country"=>"Estonia"],
            ["name"=>"eg.svg","country"=>"Egypt"],
            ["name"=>"eh.svg","country"=>"Western Sahara"],
            ["name"=>"er.svg","country"=>"Eritrea"],
            ["name"=>"es.svg","country"=>"Spain"],
            ["name"=>"et.svg","country"=>"Ethiopia"],
            ["name"=>"eu.svg","country"=>"Europe"],
            ["name"=>"fi.svg","country"=>"Finland"],
            ["name"=>"fj.svg","country"=>"Fiji"],
            ["name"=>"fk.svg","country"=>"Falkland Islands (Malvinas)"],
            ["name"=>"fm.svg","country"=>"Micronesia, Federated States Of"],
            ["name"=>"fo.svg","country"=>"Faroe Islands"],
            ["name"=>"fr.svg","country"=>"France"],
            ["name"=>"ga.svg","country"=>"Gabon"],
            ["name"=>"gb-eng.svg","country"=>"England"],
            ["name"=>"gb-nir.svg","country"=>"Northern Ireland"],
            ["name"=>"gb-sct.svg","country"=>"Scotland"],
            ["name"=>"gb-wls.svg","country"=>"Wales"],
            ["name"=>"gb.svg","country"=>"United Kingdom"],
            ["name"=>"gd.svg","country"=>"Grenada"],
            ["name"=>"ge.svg","country"=>"Georgia"],
            ["name"=>"gf.svg","country"=>"French Guiana"],
            ["name"=>"gg.svg","country"=>"Guernsey"],
            ["name"=>"gh.svg","country"=>"Ghana"],
            ["name"=>"gi.svg","country"=>"Gibraltar"],
            ["name"=>"gl.svg","country"=>"Greenland"],
            ["name"=>"gm.svg","country"=>"Gambia"],
            ["name"=>"gn.svg","country"=>"Guinea"],
            ["name"=>"gp.svg","country"=>"Guadeloupe"],
            ["name"=>"gq.svg","country"=>"Equatorial Guinea"],
            ["name"=>"gr.svg","country"=>"Greece"],
            ["name"=>"gs.svg","country"=>"South Georgia And The South Sandwich Islands"],
            ["name"=>"gt.svg","country"=>"Guatemala"],
            ["name"=>"gu.svg","country"=>"Guam"],
            ["name"=>"gw.svg","country"=>"Guinea-Bissau"],
            ["name"=>"gy.svg","country"=>"Guyana"],
            ["name"=>"hk.svg","country"=>"Hong Kong"],
            ["name"=>"hm.svg","country"=>"Heard Island And McDonald Islands"],
            ["name"=>"hn.svg","country"=>"Honduras"],
            ["name"=>"hr.svg","country"=>"Croatia"],
            ["name"=>"ht.svg","country"=>"Haiti"],
            ["name"=>"hu.svg","country"=>"Hungary"],
            ["name"=>"id.svg","country"=>"Indonesia"],
            ["name"=>"ie.svg","country"=>"Ireland"],
            ["name"=>"il.svg","country"=>"Israel"],
            ["name"=>"im.svg","country"=>"Isle Of Man"],
            ["name"=>"in.svg","country"=>"India"],
            ["name"=>"io.svg","country"=>"British Indian Ocean Territory"],
            ["name"=>"iq.svg","country"=>"Iraq"],
            ["name"=>"ir.svg","country"=>"Iran, Islamic Republic Of"],
            ["name"=>"is.svg","country"=>"Iceland"],
            ["name"=>"it.svg","country"=>"Italy"],
            ["name"=>"je.svg","country"=>"Jersey"],
            ["name"=>"jm.svg","country"=>"Jamaica"],
            ["name"=>"jo.svg","country"=>"Jordan"],
            ["name"=>"jp.svg","country"=>"Japan"],
            ["name"=>"ke.svg","country"=>"Kenya"],
            ["name"=>"kg.svg","country"=>"Kyrgyzstan"],
            ["name"=>"kh.svg","country"=>"Cambodia"],
            ["name"=>"ki.svg","country"=>"Kiribati"],
            ["name"=>"km.svg","country"=>"Comoros"],
            ["name"=>"kn.svg","country"=>"Saint Kitts And Nevis"],
            ["name"=>"kp.svg","country"=>"Korea, Democratic People's Republic Of"],
            ["name"=>"kr.svg","country"=>"Korea, Republic Of"],
            ["name"=>"kw.svg","country"=>"Kuwait"],
            ["name"=>"ky.svg","country"=>"Cayman Islands"],
            ["name"=>"kz.svg","country"=>"Kazakhstan"],
            ["name"=>"la.svg","country"=>"Laos (Lao People's Democratic Republic)"],
            ["name"=>"lb.svg","country"=>"Lebanon"],
            ["name"=>"lc.svg","country"=>"Saint Lucia"],
            ["name"=>"li.svg","country"=>"Liechtenstein"],
            ["name"=>"lk.svg","country"=>"Sri Lanka"],
            ["name"=>"lr.svg","country"=>"Liberia"],
            ["name"=>"ls.svg","country"=>"Lesotho"],
            ["name"=>"lt.svg","country"=>"Lithuania"],
            ["name"=>"lu.svg","country"=>"Luxembourg"],
            ["name"=>"lv.svg","country"=>"Latvia"],
            ["name"=>"ly.svg","country"=>"Libya"],
            ["name"=>"ma.svg","country"=>"Morocco"],
            ["name"=>"mc.svg","country"=>"Monaco"],
            ["name"=>"md.svg","country"=>"Moldova, Republic Of"],
            ["name"=>"me.svg","country"=>"Montenegro"],
            ["name"=>"mf.svg","country"=>"Saint Martin"],
            ["name"=>"mg.svg","country"=>"Madagascar"],
            ["name"=>"mh.svg","country"=>"Marshall Islands"],
            ["name"=>"mk.svg","country"=>"North Macedonia"],
            ["name"=>"ml.svg","country"=>"Mali"],
            ["name"=>"mm.svg","country"=>"Myanmar"],
            ["name"=>"mn.svg","country"=>"Mongolia"],
            ["name"=>"mo.svg","country"=>"Macao"],
            ["name"=>"mp.svg","country"=>"Northern Mariana Islands"],
            ["name"=>"mq.svg","country"=>"Martinique"],
            ["name"=>"mr.svg","country"=>"Mauritania"],
            ["name"=>"ms.svg","country"=>"Montserrat"],
            ["name"=>"mt.svg","country"=>"Malta"],
            ["name"=>"mu.svg","country"=>"Mauritius"],
            ["name"=>"mv.svg","country"=>"Maldives"],
            ["name"=>"mw.svg","country"=>"Malawi"],
            ["name"=>"mx.svg","country"=>"Mexico"],
            ["name"=>"my.svg","country"=>"Malaysia"],
            ["name"=>"mz.svg","country"=>"Mozambique"],
            ["name"=>"na.svg","country"=>"Namibia"],
            ["name"=>"nc.svg","country"=>"New Caledonia"],
            ["name"=>"ne.svg","country"=>"Niger"],
            ["name"=>"nf.svg","country"=>"Norfolk Island"],
            ["name"=>"ng.svg","country"=>"Nigeria"],
            ["name"=>"ni.svg","country"=>"Nicaragua"],
            ["name"=>"nl.svg","country"=>"Netherlands"],
            ["name"=>"no.svg","country"=>"Norway"],
            ["name"=>"np.svg","country"=>"Nepal"],
            ["name"=>"nr.svg","country"=>"Nauru"],
            ["name"=>"nu.svg","country"=>"Niue"],
            ["name"=>"nz.svg","country"=>"New Zealand"],
            ["name"=>"om.svg","country"=>"Oman"],
            ["name"=>"pa.svg","country"=>"Panama"],
            ["name"=>"pe.svg","country"=>"Peru"],
            ["name"=>"pf.svg","country"=>"French Polynesia"],
            ["name"=>"pg.svg","country"=>"Papua New Guinea"],
            ["name"=>"ph.svg","country"=>"Philippines"],
            ["name"=>"pk.svg","country"=>"Pakistan"],
            ["name"=>"pl.svg","country"=>"Poland"],
            ["name"=>"pm.svg","country"=>"Saint Pierre And Miquelon"],
            ["name"=>"pn.svg","country"=>"Pitcairn"],
            ["name"=>"pr.svg","country"=>"Puerto Rico"],
            ["name"=>"ps.svg","country"=>"Palestine"],
            ["name"=>"pt.svg","country"=>"Portugal"],
            ["name"=>"pw.svg","country"=>"Palau"],
            ["name"=>"py.svg","country"=>"Paraguay"],
            ["name"=>"qa.svg","country"=>"Qatar"],
            ["name"=>"re.svg","country"=>"Réunion"],
            ["name"=>"ro.svg","country"=>"Romania"],
            ["name"=>"rs.svg","country"=>"Serbia"],
            ["name"=>"ru.svg","country"=>"Russian Federation"],
            ["name"=>"rw.svg","country"=>"Rwanda"],
            ["name"=>"sa.svg","country"=>"Saudi Arabia"],
            ["name"=>"sb.svg","country"=>"Solomon Islands"],
            ["name"=>"sc.svg","country"=>"Seychelles"],
            ["name"=>"sd.svg","country"=>"Sudan"],
            ["name"=>"se.svg","country"=>"Sweden"],
            ["name"=>"sg.svg","country"=>"Singapore"],
            ["name"=>"sh.svg","country"=>"Saint Helena, Ascension And Tristan Da Cunha"],
            ["name"=>"si.svg","country"=>"Slovenia"],
            ["name"=>"sj.svg","country"=>"Svalbard And Jan Mayen Islands"],
            ["name"=>"sk.svg","country"=>"Slovakia"],
            ["name"=>"sl.svg","country"=>"Sierra Leone"],
            ["name"=>"sm.svg","country"=>"San Marino"],
            ["name"=>"sn.svg","country"=>"Senegal"],
            ["name"=>"so.svg","country"=>"Somalia"],
            ["name"=>"sr.svg","country"=>"Suriname"],
            ["name"=>"ss.svg","country"=>"South Sudan"],
            ["name"=>"st.svg","country"=>"Sao Tome And Principe"],
            ["name"=>"sv.svg","country"=>"El Salvador"],
            ["name"=>"sx.svg","country"=>"Sint Maarten (Dutch Part)"],
            ["name"=>"sy.svg","country"=>"Syrian Arab Republic"],
            ["name"=>"sz.svg","country"=>"Swaziland"],
            ["name"=>"tc.svg","country"=>"Turks And Caicos Islands"],
            ["name"=>"td.svg","country"=>"Chad"],
            ["name"=>"tf.svg","country"=>"French Southern Territories"],
            ["name"=>"tg.svg","country"=>"Togo"],
            ["name"=>"th.svg","country"=>"Thailand"],
            ["name"=>"tj.svg","country"=>"Tajikistan"],
            ["name"=>"tk.svg","country"=>"Tokelau"],
            ["name"=>"tl.svg","country"=>"Timor-Leste"],
            ["name"=>"tm.svg","country"=>"Turkmenistan"],
            ["name"=>"tn.svg","country"=>"Tunisia"],
            ["name"=>"to.svg","country"=>"Tonga"],
            ["name"=>"tr.svg","country"=>"Turkey"],
            ["name"=>"tt.svg","country"=>"Trinidad And Tobago"],
            ["name"=>"tv.svg","country"=>"Tuvalu"],
            ["name"=>"tw.svg","country"=>"Taiwan (Republic Of China)"],
            ["name"=>"tz.svg","country"=>"Tanzania, United Republic Of"],
            ["name"=>"ua.svg","country"=>"Ukraine"],
            ["name"=>"ug.svg","country"=>"Uganda"],
            ["name"=>"um.svg","country"=>"US Minor Outlying Islands"],
            ["name"=>"us.svg","country"=>"United States"],
            ["name"=>"uy.svg","country"=>"Uruguay"],
            ["name"=>"uz.svg","country"=>"Uzbekistan"],
            ["name"=>"va.svg","country"=>"Holy See (Vatican City State)"],
            ["name"=>"vc.svg","country"=>"Saint Vincent And The Grenadines"],
            ["name"=>"ve.svg","country"=>"Venezuela, Bolivarian Republic Of"],
            ["name"=>"vg.svg","country"=>"Virgin Islands, British"],
            ["name"=>"vi.svg","country"=>"Virgin Islands, U.S."],
            ["name"=>"vn.svg","country"=>"Vietnam"],
            ["name"=>"vu.svg","country"=>"Vanuatu"],
            ["name"=>"wf.svg","country"=>"Wallis And Futuna Islands"],
            ["name"=>"ws.svg","country"=>"Samoa"],
            ["name"=>"xk.svg","country"=>"Kosovo"],
            ["name"=>"ye.svg","country"=>"Yemen"],
            ["name"=>"yt.svg","country"=>"Mayotte"],
            ["name"=>"za.svg","country"=>"South Africa"],
            ["name"=>"zm.svg","country"=>"Zambia"],
            ["name"=>"zw.svg","country"=>"Zimbabwe"],
            ["name"=>"ad.svg","country"=>"Andorra"],
            ["name"=>"ae.svg","country"=>"United Arab Emirates"],
            ["name"=>"af.svg","country"=>"Afghanistan"],
            ["name"=>"ag.svg","country"=>"Antigua And Barbuda"],
            ["name"=>"ai.svg","country"=>"Anguilla"],
            ["name"=>"al.svg","country"=>"Albania"],
            ["name"=>"am.svg","country"=>"Armenia"],
            ["name"=>"ao.svg","country"=>"Angola"],
            ["name"=>"aq.svg","country"=>"Antarctica"],
            ["name"=>"ar.svg","country"=>"Argentina"],
            ["name"=>"as.svg","country"=>"American Samoa"],
            ["name"=>"at.svg","country"=>"Austria"],
            ["name"=>"au.svg","country"=>"Australia"],
            ["name"=>"aw.svg","country"=>"Aruba"],
            ["name"=>"ax.svg","country"=>"Åland Islands"],
            ["name"=>"az.svg","country"=>"Azerbaijan"],
            ["name"=>"ba.svg","country"=>"Bosnia And Herzegovina"],
            ["name"=>"bb.svg","country"=>"Barbados"],
            ["name"=>"bd.svg","country"=>"Bangladesh"],
            ["name"=>"be.svg","country"=>"Belgium"],
            ["name"=>"bf.svg","country"=>"Burkina Faso"],
            ["name"=>"bg.svg","country"=>"Bulgaria"],
            ["name"=>"bh.svg","country"=>"Bahrain"],
            ["name"=>"bi.svg","country"=>"Burundi"],
            ["name"=>"bj.svg","country"=>"Benin"],
            ["name"=>"bl.svg","country"=>"Saint Barthélemy"],
            ["name"=>"bm.svg","country"=>"Bermuda"],
            ["name"=>"bn.svg","country"=>"Brunei Darussalam"],
            ["name"=>"bo.svg","country"=>"Bolivia, Plurinational State Of"],
            ["name"=>"bq.svg","country"=>"Caribbean Netherlands"],
            ["name"=>"br.svg","country"=>"Brazil"],
            ["name"=>"bs.svg","country"=>"Bahamas"],
            ["name"=>"bt.svg","country"=>"Bhutan"],
            ["name"=>"bv.svg","country"=>"Bouvet Island"],
            ["name"=>"bw.svg","country"=>"Botswana"],
            ["name"=>"by.svg","country"=>"Belarus"],
            ["name"=>"bz.svg","country"=>"Belize"],
            ["name"=>"ca.svg","country"=>"Canada"],
            ["name"=>"cc.svg","country"=>"Cocos (Keeling) Islands"],
            ["name"=>"cd.svg","country"=>"Congo, The Democratic Republic Of The"],
            ["name"=>"cf.svg","country"=>"Central African Republic"],
            ["name"=>"cg.svg","country"=>"Republic Of The Congo"],
            ["name"=>"ch.svg","country"=>"Switzerland"],
            ["name"=>"ci.svg","country"=>"Côte D'Ivoire"],
            ["name"=>"ck.svg","country"=>"Cook Islands"],
            ["name"=>"cl.svg","country"=>"Chile"],
            ["name"=>"cm.svg","country"=>"Cameroon"],
            ["name"=>"cn.svg","country"=>"China (People's Republic Of China)"],
            ["name"=>"co.svg","country"=>"Colombia"],
            ["name"=>"cr.svg","country"=>"Costa Rica"],
            ["name"=>"cu.svg","country"=>"Cuba"],
            ["name"=>"cv.svg","country"=>"Cape Verde"],
            ["name"=>"cw.svg","country"=>"Curaçao"],
            ["name"=>"cx.svg","country"=>"Christmas Island"],
            ["name"=>"cy.svg","country"=>"Cyprus"],
            ["name"=>"cz.svg","country"=>"Czech Republic"],
            ["name"=>"de.svg","country"=>"Germany"],
            ["name"=>"dj.svg","country"=>"Djibouti"],
            ["name"=>"dk.svg","country"=>"Denmark"],
            ["name"=>"dm.svg","country"=>"Dominica"],
            ["name"=>"do.svg","country"=>"Dominican Republic"],
            ["name"=>"dz.svg","country"=>"Algeria"],
            ["name"=>"ec.svg","country"=>"Ecuador"],
            ["name"=>"ee.svg","country"=>"Estonia"],
            ["name"=>"eg.svg","country"=>"Egypt"],
            ["name"=>"eh.svg","country"=>"Western Sahara"],
            ["name"=>"er.svg","country"=>"Eritrea"],
            ["name"=>"es.svg","country"=>"Spain"],
            ["name"=>"et.svg","country"=>"Ethiopia"],
            ["name"=>"eu.svg","country"=>"Europe"],
            ["name"=>"fi.svg","country"=>"Finland"],
            ["name"=>"fj.svg","country"=>"Fiji"],
            ["name"=>"fk.svg","country"=>"Falkland Islands (Malvinas)"],
            ["name"=>"fm.svg","country"=>"Micronesia, Federated States Of"],
            ["name"=>"fo.svg","country"=>"Faroe Islands"],
            ["name"=>"fr.svg","country"=>"France"],
            ["name"=>"ga.svg","country"=>"Gabon"],
            ["name"=>"gb-eng.svg","country"=>"England"],
            ["name"=>"gb-nir.svg","country"=>"Northern Ireland"],
            ["name"=>"gb-sct.svg","country"=>"Scotland"],
            ["name"=>"gb-wls.svg","country"=>"Wales"],
            ["name"=>"gb.svg","country"=>"United Kingdom"],
            ["name"=>"gd.svg","country"=>"Grenada"],
            ["name"=>"ge.svg","country"=>"Georgia"],
            ["name"=>"gf.svg","country"=>"French Guiana"],
            ["name"=>"gg.svg","country"=>"Guernsey"],
            ["name"=>"gh.svg","country"=>"Ghana"],
            ["name"=>"gi.svg","country"=>"Gibraltar"],
            ["name"=>"gl.svg","country"=>"Greenland"],
            ["name"=>"gm.svg","country"=>"Gambia"],
            ["name"=>"gn.svg","country"=>"Guinea"],
            ["name"=>"gp.svg","country"=>"Guadeloupe"],
            ["name"=>"gq.svg","country"=>"Equatorial Guinea"],
            ["name"=>"gr.svg","country"=>"Greece"],
            ["name"=>"gs.svg","country"=>"South Georgia And The South Sandwich Islands"],
            ["name"=>"gt.svg","country"=>"Guatemala"],
            ["name"=>"gu.svg","country"=>"Guam"],
            ["name"=>"gw.svg","country"=>"Guinea-Bissau"],
            ["name"=>"gy.svg","country"=>"Guyana"],
            ["name"=>"hk.svg","country"=>"Hong Kong"],
            ["name"=>"hm.svg","country"=>"Heard Island And McDonald Islands"],
            ["name"=>"hn.svg","country"=>"Honduras"],
            ["name"=>"hr.svg","country"=>"Croatia"],
            ["name"=>"ht.svg","country"=>"Haiti"],
            ["name"=>"hu.svg","country"=>"Hungary"],
            ["name"=>"id.svg","country"=>"Indonesia"],
            ["name"=>"ie.svg","country"=>"Ireland"],
            ["name"=>"il.svg","country"=>"Israel"],
            ["name"=>"im.svg","country"=>"Isle Of Man"],
            ["name"=>"in.svg","country"=>"India"],
            ["name"=>"io.svg","country"=>"British Indian Ocean Territory"],
            ["name"=>"iq.svg","country"=>"Iraq"],
            ["name"=>"ir.svg","country"=>"Iran, Islamic Republic Of"],
            ["name"=>"is.svg","country"=>"Iceland"],
            ["name"=>"it.svg","country"=>"Italy"],
            ["name"=>"je.svg","country"=>"Jersey"],
            ["name"=>"jm.svg","country"=>"Jamaica"],
            ["name"=>"jo.svg","country"=>"Jordan"],
            ["name"=>"jp.svg","country"=>"Japan"],
            ["name"=>"ke.svg","country"=>"Kenya"],
            ["name"=>"kg.svg","country"=>"Kyrgyzstan"],
            ["name"=>"kh.svg","country"=>"Cambodia"],
            ["name"=>"ki.svg","country"=>"Kiribati"],
            ["name"=>"km.svg","country"=>"Comoros"],
            ["name"=>"kn.svg","country"=>"Saint Kitts And Nevis"],
            ["name"=>"kp.svg","country"=>"Korea, Democratic People's Republic Of"],
            ["name"=>"kr.svg","country"=>"Korea, Republic Of"],
            ["name"=>"kw.svg","country"=>"Kuwait"],
            ["name"=>"ky.svg","country"=>"Cayman Islands"],
            ["name"=>"kz.svg","country"=>"Kazakhstan"],
            ["name"=>"la.svg","country"=>"Laos (Lao People's Democratic Republic)"],
            ["name"=>"lb.svg","country"=>"Lebanon"],
            ["name"=>"lc.svg","country"=>"Saint Lucia"],
            ["name"=>"li.svg","country"=>"Liechtenstein"],
            ["name"=>"lk.svg","country"=>"Sri Lanka"],
            ["name"=>"lr.svg","country"=>"Liberia"],
            ["name"=>"ls.svg","country"=>"Lesotho"],
            ["name"=>"lt.svg","country"=>"Lithuania"],
            ["name"=>"lu.svg","country"=>"Luxembourg"],
            ["name"=>"lv.svg","country"=>"Latvia"],
            ["name"=>"ly.svg","country"=>"Libya"],
            ["name"=>"ma.svg","country"=>"Morocco"],
            ["name"=>"mc.svg","country"=>"Monaco"],
            ["name"=>"md.svg","country"=>"Moldova, Republic Of"],
            ["name"=>"me.svg","country"=>"Montenegro"],
            ["name"=>"mf.svg","country"=>"Saint Martin"],
            ["name"=>"mg.svg","country"=>"Madagascar"],
            ["name"=>"mh.svg","country"=>"Marshall Islands"],
            ["name"=>"mk.svg","country"=>"North Macedonia"],
            ["name"=>"ml.svg","country"=>"Mali"],
            ["name"=>"mm.svg","country"=>"Myanmar"],
            ["name"=>"mn.svg","country"=>"Mongolia"],
            ["name"=>"mo.svg","country"=>"Macao"],
            ["name"=>"mp.svg","country"=>"Northern Mariana Islands"],
            ["name"=>"mq.svg","country"=>"Martinique"],
            ["name"=>"mr.svg","country"=>"Mauritania"],
            ["name"=>"ms.svg","country"=>"Montserrat"],
            ["name"=>"mt.svg","country"=>"Malta"],
            ["name"=>"mu.svg","country"=>"Mauritius"],
            ["name"=>"mv.svg","country"=>"Maldives"],
            ["name"=>"mw.svg","country"=>"Malawi"],
            ["name"=>"mx.svg","country"=>"Mexico"],
            ["name"=>"my.svg","country"=>"Malaysia"],
            ["name"=>"mz.svg","country"=>"Mozambique"],
            ["name"=>"na.svg","country"=>"Namibia"],
            ["name"=>"nc.svg","country"=>"New Caledonia"],
            ["name"=>"ne.svg","country"=>"Niger"],
            ["name"=>"nf.svg","country"=>"Norfolk Island"],
            ["name"=>"ng.svg","country"=>"Nigeria"],
            ["name"=>"ni.svg","country"=>"Nicaragua"],
            ["name"=>"nl.svg","country"=>"Netherlands"],
            ["name"=>"no.svg","country"=>"Norway"],
            ["name"=>"np.svg","country"=>"Nepal"],
            ["name"=>"nr.svg","country"=>"Nauru"],
            ["name"=>"nu.svg","country"=>"Niue"],
            ["name"=>"nz.svg","country"=>"New Zealand"],
            ["name"=>"om.svg","country"=>"Oman"],
            ["name"=>"pa.svg","country"=>"Panama"],
            ["name"=>"pe.svg","country"=>"Peru"],
            ["name"=>"pf.svg","country"=>"French Polynesia"],
            ["name"=>"pg.svg","country"=>"Papua New Guinea"],
            ["name"=>"ph.svg","country"=>"Philippines"],
            ["name"=>"pk.svg","country"=>"Pakistan"],
            ["name"=>"pl.svg","country"=>"Poland"],
            ["name"=>"pm.svg","country"=>"Saint Pierre And Miquelon"],
            ["name"=>"pn.svg","country"=>"Pitcairn"],
            ["name"=>"pr.svg","country"=>"Puerto Rico"],
            ["name"=>"ps.svg","country"=>"Palestine"],
            ["name"=>"pt.svg","country"=>"Portugal"],
            ["name"=>"pw.svg","country"=>"Palau"],
            ["name"=>"py.svg","country"=>"Paraguay"],
            ["name"=>"qa.svg","country"=>"Qatar"],
            ["name"=>"re.svg","country"=>"Réunion"],
            ["name"=>"ro.svg","country"=>"Romania"],
            ["name"=>"rs.svg","country"=>"Serbia"],
            ["name"=>"ru.svg","country"=>"Russian Federation"],
            ["name"=>"rw.svg","country"=>"Rwanda"],
            ["name"=>"sa.svg","country"=>"Saudi Arabia"],
            ["name"=>"sb.svg","country"=>"Solomon Islands"],
            ["name"=>"sc.svg","country"=>"Seychelles"],
            ["name"=>"sd.svg","country"=>"Sudan"],
            ["name"=>"se.svg","country"=>"Sweden"],
            ["name"=>"sg.svg","country"=>"Singapore"],
            ["name"=>"sh.svg","country"=>"Saint Helena, Ascension And Tristan Da Cunha"],
            ["name"=>"si.svg","country"=>"Slovenia"],
            ["name"=>"sj.svg","country"=>"Svalbard And Jan Mayen Islands"],
            ["name"=>"sk.svg","country"=>"Slovakia"],
            ["name"=>"sl.svg","country"=>"Sierra Leone"],
            ["name"=>"sm.svg","country"=>"San Marino"],
            ["name"=>"sn.svg","country"=>"Senegal"],
            ["name"=>"so.svg","country"=>"Somalia"],
            ["name"=>"sr.svg","country"=>"Suriname"],
            ["name"=>"ss.svg","country"=>"South Sudan"],
            ["name"=>"st.svg","country"=>"Sao Tome And Principe"],
            ["name"=>"sv.svg","country"=>"El Salvador"],
            ["name"=>"sx.svg","country"=>"Sint Maarten (Dutch Part)"],
            ["name"=>"sy.svg","country"=>"Syrian Arab Republic"],
            ["name"=>"sz.svg","country"=>"Swaziland"],
            ["name"=>"tc.svg","country"=>"Turks And Caicos Islands"],
            ["name"=>"td.svg","country"=>"Chad"],
            ["name"=>"tf.svg","country"=>"French Southern Territories"],
            ["name"=>"tg.svg","country"=>"Togo"],
            ["name"=>"th.svg","country"=>"Thailand"],
            ["name"=>"tj.svg","country"=>"Tajikistan"],
            ["name"=>"tk.svg","country"=>"Tokelau"],
            ["name"=>"tl.svg","country"=>"Timor-Leste"],
            ["name"=>"tm.svg","country"=>"Turkmenistan"],
            ["name"=>"tn.svg","country"=>"Tunisia"],
            ["name"=>"to.svg","country"=>"Tonga"],
            ["name"=>"tr.svg","country"=>"Turkey"],
            ["name"=>"tt.svg","country"=>"Trinidad And Tobago"],
            ["name"=>"tv.svg","country"=>"Tuvalu"],
            ["name"=>"tw.svg","country"=>"Taiwan (Republic Of China)"],
            ["name"=>"tz.svg","country"=>"Tanzania, United Republic Of"],
            ["name"=>"ua.svg","country"=>"Ukraine"],
            ["name"=>"ug.svg","country"=>"Uganda"],
            ["name"=>"um.svg","country"=>"US Minor Outlying Islands"],
            ["name"=>"us.svg","country"=>"United States"],
            ["name"=>"uy.svg","country"=>"Uruguay"],
            ["name"=>"uz.svg","country"=>"Uzbekistan"],
            ["name"=>"va.svg","country"=>"Holy See (Vatican City State)"],
            ["name"=>"vc.svg","country"=>"Saint Vincent And The Grenadines"],
            ["name"=>"ve.svg","country"=>"Venezuela, Bolivarian Republic Of"],
            ["name"=>"vg.svg","country"=>"Virgin Islands, British"],
            ["name"=>"vi.svg","country"=>"Virgin Islands, U.S."],
            ["name"=>"vn.svg","country"=>"Vietnam"],
            ["name"=>"vu.svg","country"=>"Vanuatu"],
            ["name"=>"wf.svg","country"=>"Wallis And Futuna Islands"],
            ["name"=>"ws.svg","country"=>"Samoa"],
            ["name"=>"xk.svg","country"=>"Kosovo"],
            ["name"=>"ye.svg","country"=>"Yemen"],
            ["name"=>"yt.svg","country"=>"Mayotte"],
            ["name"=>"za.svg","country"=>"South Africa"],
            ["name"=>"zm.svg","country"=>"Zambia"],
            ["name"=>"zw.svg","country"=>"Zimbabwe"]
        );

        foreach($images as $image){
            Image::create($image);
        }
    }
}
